version: '3.7'
services:
  app:
    container_name: user-api-app
    restart: always
    build: .
    volumes:
      - .:/app/user-api
      - ~/.m2:/root/.m2
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/user_db
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks: 
      - backend
    command: mvn spring-boot:run

  mongodb:
    container_name: user-api-db
    image: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017
    networks: 
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local
    name: mongo-data
  